# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 988d55383aaf01cfe0ced59a7a934e4fe87dffe1ef0c2c1a66e4234ee3e4d18a3fc9c08dca931062f64c0e6f1541560ac4debe5741388aa50fbc375e96436651

test:
  secret_key_base: e820594b01019edd8eceeca995e14c2cb30a5c75d64b6b07644b2fbefd16c8df8114be1f02d56ee19c13ab3a65f66624c40bc2742620a54a5e60d0351c5ef4b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
